INSERT INTO lis458olfa22_dillonk2_project.herbs (herb_id, herb_scientific_name) VALUES
(1, 'Sambucus nigra'),
(2, 'Allium  sativum'),
(3, 'Garcinia gummi-gutta'),
(4, 'Glycine max'),
(5, 'Matricaria recutita'),
(6, 'Ephedra sinica'),
(7, 'Zingiber officinale'),
(8, 'Vitis vinifera'),
(9, 'Uncaria tomentosa'),
(10, 'Hydrastis canadensis'),
(11, 'Passiflora incarnata'),
(12, 'Pausinystalia yohimbe'),
(13, 'Vaccinium myrtillus'),
(14, 'Aloe vera'),
(15, 'Trifolium pratense'),
(16, 'Serenoa repens'),
(17, 'Salvia officinalis'),
(18, 'Artemisia vulgaris'),
(19, 'Vitex agnus-castus'),
(20, 'Camellia sinensis'),
(21, 'Curcuma longa'),
(22, 'Actaea racemosa'),
(23, 'Echinacea purpurea'),
(24, 'Panax ginseng'),
(25, 'Ginkgo biloba'),
(26, 'Cinnamomum verum '),
(27, 'Citrus aurantium'),
(28, 'Oenothera biennis'),
(29, 'Trigonella foenum-graecum'),
(30, 'Astragalus membranaceus'),
(31, 'Hoodia gordonii'),
(32, 'Tanacetum parthenium'),
(33, ''),
(34, 'Glycyrrhiza glabra'),
(35, 'Viscum album'),
(36, 'Taraxacum officinale'),
(37, 'Piper methysticum'),
(38, 'Hypericum perforatum'),
(39, 'Punica granatum'),
(40, 'Crataegus monogyna'),
(41, 'Vaccinium macrocarpon '),
(42, 'Tripterygium wilfordii'),
(43, 'Valeriana officinalis'),
(44, 'Linum usitatissimum'),
(45, 'Morinda citrifolia'),
(46, 'Mentha x piperita'),
(47, 'Rhodiola rosea'),
(48, 'Euterpe oleracea'),
(49, 'Silybum marianum'),
(50, 'Melaleuca alternifolia'),
(51, 'Lavandula angustifolia'),
(52, 'Petasites hybridus '),
(53, 'Aesculus hippocastanum');