INSERT INTO lis458olfa22_dillonk2_project.common_names (common_name, herb_id) VALUES
('European elder', 1),
('black elder', 1),
('elderberry', 1),
('elder flower', 1),
('sambucus', 1),
('garlic', 2),
('garcinia cambogia', 3),
('garcinia', 3),
('Malabar tamarind', 3),
('brindle berry', 3),
('soy', 4),
('chamomile', 5),
('German chamomile', 5),
('ephedra', 6),
('Chinese ephedra', 6),
('ma huang', 6),
('ginger', 7),
('grape seed extract', 8),
('grape seed', 8),
('cat’s claw', 9),
('uña de gato', 9),
('goldenseal', 10),
('yellow root', 10),
('passionflower', 11),
('maypop', 11),
('apricot vine', 11),
('maracuja', 11),
('water lemon', 11),
('yohimbe', 12),
('johimbi', 12),
('bilberry', 13),
('European blueberry', 13),
('whortleberry', 13),
('huckleberry', 13),
('aloe', 14),
('red clover', 15),
('cow clover', 15),
('meadow clover', 15),
('wild clover', 15),
('saw palmetto', 16),
('American dwarf palm tree', 16),
('cabbage palm', 16),
('sage', 17),
('common sage', 17),
('garden sage', 17),
('true sage', 17),
('mugwort', 18),
('common wormwood', 18),
('wild wormwood', 18),
('felon herb', 18),
('chrysanthemum weed', 18),
('St. John’s plant', 18),
('sailor’s tobacco', 18),
('chasteberry', 19),
('chaste tree', 19),
('vitex', 19),
("monk's pepper", 19),
('green tea', 20),
('turmeric', 21),
('turmeric root', 21),
('Indian saffron', 21),
('black cohosh', 22),
('black snakeroot', 22),
('macrotys', 22),
('bugbane', 22),
('bugwort', 22),
('rattleroot', 22),
('rattleweed', 22),
('echinacea', 23),
('purple coneflower', 23),
('coneflower', 23),
('American coneflower', 23),
('Asian ginseng', 24),
('Chinese ginseng', 24),
('Korean ginseng', 24),
('red ginseng', 24),
('white ginseng', 24),
('ginkgo', 25),
('Ginkgo biloba', 25),
('fossil tree', 25),
('maidenhair tree', 25),
('Japanese silver apricot', 25),
('baiguo', 25),
('yinhsing', 25),
('cinnamon', 26),
('cinnamon bark', 26),
('Ceylon cinnamon', 26),
('cassia cinnamon', 26),
('bitter orange', 27),
('Seville orange', 27),
('sour orange', 27),
('zhi shi', 27),
('evening primrose oil', 28),
('EPO', 28),
('fenugreek', 29),
('astragale', 30),
('astragale à feuilles de réglisse', 30),
('beg kei', 30),
('milk vetch', 30),
('hoodia', 31),
('Kalahari cactus', 31),
('Xhoba', 31),
('feverfew', 32),
('bachelor’s buttons', 32),
('featherfew', 32),
('bromelain', 33),
('pineapple enzyme', 33),
('pineapple extract', 33),
('licorice root', 34),
('licorice', 34),
('liquorice', 34),
('sweet root', 34),
('gan cao', 34),
('gan zao', 34),
('Chinese licorice', 34),
('European mistletoe', 35),
('dandelion', 36),
('lion’s tooth', 36),
('blowball', 36),
('kava', 37),
('kava kava', 37),
('ava pepper', 37),
('ava root', 37),
('kawa', 37),
('St. John’s wort', 38),
('hypericum', 38),
('Klamath weed', 38),
('goatweed', 38),
('Pomegranate', 39),
('hawthorn', 40),
('English hawthorn', 40),
('oneseed hawthorn', 40),
('harthorne', 40),
('haw', 40),
('hawthorne', 40),
('cranberry', 41),
('American cranberry', 41),
('bearberry', 41),
('thunder god vine', 42),
('lei gong teng', 42),
('valerian', 43),
('all-heal', 43),
('garden heliotrope', 43),
('flaxseed', 44),
('flax', 44),
('linseed', 44),
('noni', 45),
('morinda', 45),
('Indian mulberry', 45),
('hog apple', 45),
('canarywood', 45),
('peppermint', 46),
('peppermint oil', 46),
('arctic root', 47),
('golden root', 47),
('rose root', 47),
('king’s crown', 47),
('acai', 48),
('acai berry', 48),
('açaí', 48),
('milk thistle', 49),
('Mary thistle', 49),
('holy thistle', 49),
('tea tree oil', 50),
('tea tree', 50),
('Australian tea tree oil', 50),
('tea tree essential oil', 50),
('melaleuca oil', 50),
('lavender', 51),
('English lavender', 51),
('common lavender', 51),
('French lavender', 51),
('butterbur', 52),
('petasites', 52),
('purple butterbur', 52),
('horse chestnut', 53),
('buckeye', 53),
('Spanish chestnut', 53);